[build]
  publish = "dist"  # Update to your actual build output directory
  command = "npm run build"  # Ensure this command is correct for your project

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true

