[build]
  publish = "build"       # Directory containing your built static files
  command = "npm run build" # Command to build your project

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true
